# download e installazione dipendenze pacchetto "assertive"
# NB: l'ordine deve essere quello qui sotto, per ultima la libreria assertive ... le precedenti sono le sue dipendenze
library(devtools)
install_bitbucket("richierocks/assertive.base")
install_bitbucket("richierocks/assertive.properties")
install_bitbucket("richierocks/assertive.types")
install_bitbucket("richierocks/assertive.code")
install_bitbucket("richierocks/assertive.strings")
install_bitbucket("richierocks/assertive.data")
install_bitbucket("richierocks/assertive.data.uk")
install_bitbucket("richierocks/assertive.data.us")
install_bitbucket("richierocks/assertive.datetimes")
install_bitbucket("richierocks/assertive.numbers")
install_bitbucket("richierocks/assertive.files")
install_bitbucket("richierocks/assertive.sets")
install_bitbucket("richierocks/assertive.matrices")
install_bitbucket("richierocks/assertive.models")
install_bitbucket("richierocks/assertive.reflection")
install_bitbucket("richierocks/assertive")